plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'io.horizontalsystems.oxyrakit'
    compileSdk 36

    ndkVersion '27.0.12077973'
    defaultConfig {
        minSdk 27

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
                arguments '-DANDROID_STL=c++_shared'
            }
        }
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }

    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', 'arm64-v8a'
            universalApk true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'

    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    implementation 'info.guardianproject.netcipher:netcipher:2.1.0'
    implementation 'com.nulab-inc:zxcvbn:1.9.0'
    implementation 'com.google.guava:guava:33.4.8-android'
    implementation "com.jakewharton.timber:timber:5.0.1"
    implementation "com.squareup.okhttp3:okhttp:5.3.2"
    implementation 'io.github.rburgst:okhttp-digest:3.1.1'
    implementation 'com.github.horizontalsystems:hd-wallet-kit-android:a74b51f3'
}
